#pragma once

struct Vocabulary {
  const char* word;
  const char* translation;
  const char* level;
};

const Vocabulary dailyWords[] = {
  {"Das Frühstück", "Завтрак", "A1"},
  {"Der Bahnhof", "Вокзал", "A1"},
  {"Der Nachbar", "Сосед", "A1"},
  {"Der Schlüssel", "Ключ", "A1"},
  {"Die Wohnung", "Квартира", "A1"},
  {"Einfach", "Просто", "A1"},
  {"Schnell", "Быстро", "A1"},
  {"Der Tag", "День", "A1"},
  {"Die Nacht", "Ночь", "A1"},
  {"Das Haus", "Дом", "A1"},
  {"Die Stadt", "Город", "A1"},
  {"Der Freund", "Друг", "A1"},
  {"Das Auto", "Автомобиль", "A1"},
  {"Trinken", "Пить", "A1"},
  {"Esen", "Есть (кушать)", "A1"},
  {"Schlafen", "Спать", "A1"},
  {"Sprechen", "Говорить", "A1"},
  {"Verstehen", "Понимать", "A1"},
  {"Machen", "Делать", "A1"},
  {"Gehen", "Идти", "A1"},
  {"Kommen", "Приходить", "A1"},
  {"Neu", "Новый", "A1"},
  {"Alt", "Старый", "A1"},
  {"Groß", "Большой", "A1"},
  {"Klein", "Маленький", "A1"},
  
  {"Die Verspätung", "Опоздание", "A2"},
  {"Der Arbeitsvertrag", "Рабочий контракт", "A2"},
  {"Die Anmeldung", "Регистрация", "A2"},
  {"Die Versicherung", "Страховка", "A2"},
  {"Der Termin", "Встреча/Прием", "A2"},
  {"Vorsichtig", "Осторожно", "A2"},
  {"Die Erlaubnis", "Разрешение", "A2"},
  {"Günstig", "Выгодно/Дешево", "A2"},
  {"Der Arzt", "Врач", "A2"},
  {"Die Arbeit", "Работа", "A2"},
  {"Der Urlaub", "Отпуск", "A2"},
  {"Das Geschenk", "Подарок", "A2"},
  {"Die Einladung", "Приглашение", "A2"},
  {"Das Wetter", "Погода", "A2"},
  {"Die Kleidung", "Одежда", "A2"},
  {"Finden", "Находить", "A2"},
  {"Suchen", "Искать", "A2"},
  {"Verlieren", "Терять", "A2"},
  {"Vergessen", "Забывать", "A2"},
  {"Bringen", "Приносить", "A2"},
  {"Helfen", "Помогать", "A2"},
  {"Treffen", "Встречать", "A2"},
  {"Wichtig", "Важный", "A2"},
  {"Krank", "Больной", "A2"},
  {"Müde", "Уставший", "A2"},

  {"Die Unterstützung", "Поддержка", "B1"},
  {"Die Staatsbürgerschaft", "Гражданство", "B1"},
  {"Die Erfahrung", "Опыт", "B1"},
  {"Die Entscheidung", "Решение", "B1"},
  {"Das Vorstellungsgespräch", "Собеседование", "B1"},
  {"Die Verantwortung", "Ответственность", "B1"},
  {"Erfolgreich", "Успешный", "B1"},
  {"Bestätigen", "Подтверждать", "B1"},
  {"Die Voraussetzung", "Условие/Предпосылка", "B1"},
  {"Die Ausbildung", "Проф. образование", "B1"},
  {"Der Beruf", "Профессия", "B1"},
  {"Die Zukunft", "Будущее", "B1"},
  {"Die Meinung", "Мнение", "B1"},
  {"Der Eindruck", "Впечатление", "B1"},
  {"Die Beziehung", "Отношение/Связь", "B1"},
  {"Der Vorteil", "Преимущество", "B1"},
  {"Der Nachteil", "Недостаток", "B1"},
  {"Ergänzen", "Дополнять", "B1"},
  {"Vergleichen", "Сравнивать", "B1"},
  {"Erklären", "Объяснять", "B1"},
  {"Empfehlen", "Рекомендовать", "B1"},
  {"Teilnehmen", "Участвовать", "B1"},
  {"Nützlich", "Полезный", "B1"},
  {"Gefährlich", "Опасный", "B1"},
  {"Zufrieden", "Довольный", "B1"},

  {"Die Auswirkung", "Последствие/Влияние", "B2"},
  {"Widersprüchlich", "Противоречивый", "B2"},
  {"Verwirklichen", "Осуществлять/Реализовать", "B2"},
  {"Die Behörde", "Ведомство/Инстанция", "B2"},
  {"Die Leidenschaft", "Страсть/Увлечение", "B2"},
  {"Die Gewohnheit", "Привычка", "B2"},
  {"Zweifellos", "Несомненно", "B2"},
  {"Berücksichtigen", "Учитывать", "B2"},
  {"Die Umsetzung", "Внедрение/Реализация", "B2"},
  {"Die Herausforderung", "Вызов/Сложная задача", "B2"},
  {"Die Verhandlung", "Переговоры", "B2"},
  {"Die Bedingung", "Условие", "B2"},
  {"Der Bereich", "Сфера/Область", "B2"},
  {"Die Ausnahme", "Исключение", "B2"},
  {"Die Entwicklung", "Развитие", "B2"},
  {"Der Fortschritt", "Прогресс", "B2"},
  {"Das Ergebnis", "Результат", "B2"},
  {"Beeinflussen", "Влиять", "B2"},
  {"Vermeiden", "Избегать", "B2"},
  {"Bevorzugen", "Предпочитать", "B2"},
  {"Ablehnen", "Отклонять", "B2"},
  {"Zustimmen", "Соглашаться", "B2"},
  {"Überzeugen", "Убеждать", "B2"},
  {"Effizient", "Эффективный", "B2"},
  {"Nachhaltig", "Устойчивый", "B2"}
};

const int totalWords = sizeof(dailyWords) / sizeof(dailyWords[0]);